remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
title: "My Jekyll Site"
title_separator: "-"
description: "This is my great Jekyll site! Come and find out more!"

include: ["_pages"]

author:
  name   : "Derek Jensen"
  avatar : "/assets/images/me.jpg"
  bio    : "A lifetime mid-westerner that loves teaching people about technology."
  twitter: "kreatived"

paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true